### ISSUE TITLE
v3.0.2-alpha.0 introduces a bug that causes the onDismiss() to not be called on modal dismiss

### ISSUE THREAD

**Issue by mr-moto** [gorhom/react-native-bottom-sheet#168]
# Bug

v3.0.2-alpha.0 introduces a bug that causes the `onDismiss()` to not be called on modal dismiss due to wrong animate index value calculations

https://github.com/gorhom/react-native-bottom-sheet/blob/d007c886863d5bc8e09b7ba72152e50ca4c1434b/src/components/bottomSheet/BottomSheet.tsx#L556

does not equal 0 so `handleOnChange` will never trigger thus not adjusting the index to 0 and not calling `doDismiss()` in `BottomSheetModal`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.0.2-alpha.3   |
| react-native                    | 16.13.1   |
| react-native-reanimated         | 2.0.0-rc.1   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. run example on 3.0.2-alpha.3
2. open Simple modal example
3. present modal -> dismiss modal -> present modal ( will not show again )

Describe what you expected to happen:

1. modal to appear

**Comment by gorhom** [comment]
thanks @mr-moto for spotting this issue and submitting a pr 👏

**Comment by gorhom** [comment]
this should be resolved with `3.1.0` & `2.0.3` 👍

**Comment by lexengineer** [comment]
@gorhom 
This issue is still occurs in the version `3.6.5`, when I close the `BottomSheetModal` `onDismiss` called from time to time, but not always, this seems to be critical and unpredictable, because I cannot call any handlers `onDismiss` and be sure that they will be called

**Comment by gorhom** [comment]
hi @oleksiikiselov , could you test on `v4` ?

```bash
yarn add @gorhom/bottom-sheet@4.0.0-alpha.9
```
