### ISSUE TITLE
[Bug]: Bottom Sheet does not fully open with dynamic content since v5.2.0

### ISSUE THREAD

**Issue by wfern** [gorhom/react-native-bottom-sheet#2431]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

Since version 5.2.0, or specifically after commit 5de7bd3, the bottom sheet does not fully expand when its content is dynamic (e.g., depends on a state variable).

It looks like the bottom sheet is being displayed before the content height is fully calculated. As a result, the sheet opens partially by default.

If we drag the sheet manually to the top position, it reveals the full content correctly.

This behavior was working fine in previous versions (before the above commit). I test all commits included in the 5.2.0 and this one 5de7bd3 is the one that bring the problem.

### Reproduction steps

1. Use a bottom sheet with dynamic content (e.g., conditional rendering or state-dependent list).
2. Open the sheet programmatically to its highest snap point (expand).
3. Observe that it does not fully open unless manually dragged or with static content.

You can disable the condition to render the content in the snack and see that it fully opens 

### Reproduction sample

https://snack.expo.dev/@wfern/gorhom-bottom-sheet-dont-fully-open

### Images
Previous and expected result | Current (5.2.0) result
:-------------------------:|:-------------------------:
<img  alt="Image" src="https://github.com/user-attachments/assets/0ba282ef-2ea7-4942-8bec-d2ae38cf3a88" />|<img alt="Image" src="https://github.com/user-attachments/assets/6787bf47-3c6d-46f6-96e0-fc14e2978ca2" />

### Relevant log output

```shell
No log necessary
```

**Comment by rklf** [comment]
Same issue. Thanks for reporting!

**Comment by gorhom** [comment]
it should be fixed on the next release

**Comment by rklf** [comment]
Doesn't fix for me @gorhom 

<img width="414" height="115" alt="Image" src="https://github.com/user-attachments/assets/72987c09-4f23-43ae-8bb6-d94c4de85870" />
