### ISSUE TITLE
null is not an object (evaluating 'sheetsQueueRef.current[sheetsQueueRef.current.length - 1].ref.current.minimize')

### ISSUE THREAD

**Issue by chybisov** [gorhom/react-native-bottom-sheet#292]
# Bug

I'm trying to use BottomSheetModal and it crashes with this error.
![image](https://user-images.githubusercontent.com/18644653/107957687-a0088080-6fa9-11eb-94ef-dadabb70c11f.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc0   |
| react-native-gesture-handler    | 1.10.0   |
| typescript    | 4.1.5   |

## Steps To Reproduce

1. Add BottomSheetModalProvider to the root App component.
2. Use BottomSheetModal on some screen in the app.
3. Go to that screen and present/dismiss BottomSheetModal a couple of times, then go back to previous screen and return back to screen with BottomSheetModal and it crashes.

## Code

`const SNAP_POINTS = [260];`

```
<BottomSheetModal
        ref={bottomSheetModalRef}
        index={0}
        snapPoints={SNAP_POINTS}
        handleComponent={BottomSheetHandle}
        backdropComponent={BottomSheetBackdrop}
        backgroundComponent={BottomSheetBackground}
        onDismiss={onDismiss}
      >
...
      </BottomSheetModal>
```

**Comment by theohdv** [comment]
Got the same crash on v`2.2.0`

**Comment by gorhom** [comment]
@theohdv could you create another issue for `v2`, thanks

**Comment by gorhom** [comment]
this should be fixed with `v3.3.2` 👍

**Comment by BerkeAras** [comment]
Still the same issue: `TypeError: null is not an object (evaluating 'orderModalRef.current.expand')`
Any ideas, @gorhom? 😅
