### ISSUE TITLE
BottomSheet methods do nothing when keyboard is dismissing

### ISSUE THREAD

**Issue by Ghoul2077** [gorhom/react-native-bottom-sheet#446]
# Bug

When I use onSubmitEditing prop on TextInput to collapse the bottom sheet does nothing, I am calling the collapse method on the ref of bottom sheet.

Here is a video showing this bug

https://user-images.githubusercontent.com/42601281/118681032-e07fd080-b81c-11eb-9743-77e9eab9d51f.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3  |
| react-native                    | 0.63  |
| react-native-reanimated         | 2.1.0 |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Get ref of bottom sheet
2. Have a text input with prop onSubmitEditing
3. Give onSubmitEditing a function which calls ref.current.collapse();

Describe what you expected to happen:

1. After hitting enter on the keyboard the bottom sheet should collapse

## Reproducible sample code

https://snack.expo.io/@mark11/suspicious-crackers

**Comment by nhannah** [comment]
I have been experiencing the same issue when upgrading the package. The bottom sheet is meant to open when a button is pressed and I also close the keyboard if it is open, this previously was working, but now if the keyboard is open, and thus dismissed, it does not open the bottom sheet.

**Comment by gorhom** [comment]
hi @Ghoul2077 @nhannah , this should be resolved with #427 , you could test it and let me know if it still exisits 

```bash
yarn add @gorhom/bottom-sheet@4.0.0-alpha.2
```

**Comment by Ghoul2077** [comment]
I tested with 4.0.0-alpha.2, it still does not work perfectly. In this version it at least registers collapse but gets stuck in between i.e neither fully open nor fully collapsed

here is video showing this ->

https://user-images.githubusercontent.com/42601281/119261082-5c9a5f80-bbf3-11eb-8007-dc56276ff7ea.mp4

**Comment by gorhom** [comment]
@Ghoul2077 I have tested it locally , and it works fine with Android and iOS! could you clear your cache and try again

https://user-images.githubusercontent.com/4061838/119261678-63fc4180-bbd0-11eb-845a-7c81c3b30ec7.mov

**Comment by Ghoul2077** [comment]
Yep, now it works for me too after clearing the cache 👍👍

**Comment by marco-guida** [comment]
Yup, worked for me as well. Though I did notice that since upgrading to v4, the bottom sheet will collapse when using BottomSheetTextInput and performing a state change (e.g. in onChangeText handler to update state) and keyboard will remain shown. Not sure if this is related to the fix that resolved this issue and now is overly sensitive to state changes. When removing the useState setter call, all works as expected.

**Comment by gorhom** [comment]
hi @iwantadventureinthegreatwidesomewhere, `v4` #427  still in alpha and that's why i did not announce it yet. however if you find an issue please create another issue and i'll happily try to help :)

 @Ghoul2077 i'll close this ticket 👍
